import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router';
import { ArrowLeft, Copy, Monitor, Play, Pause, SkipForward, Users, Globe2, Clock3 } from 'lucide-react';
import { useRoomQuery, useRoomCommandMutation } from '@/entities/room';
import { isWorldMatch, roles, coins } from '@/entities/world-domination';
import { EnterRoom } from '@/features/enter-room';
import { SwitchTheme } from '@/features/switch-theme';
import { WorldOrders } from '@/features/world-orders';
import { WorldDiplomacy } from '@/features/world-diplomacy';
import { WorldSummary } from '@/widgets/world-summary';
import { errorMessage } from '@/shared/api';
import { Button } from '@/shared/ui/button';

export function RoomPage({ screen = false }: { screen?: boolean }) {
  const code = (useParams().code ?? '').toUpperCase();
  const { data: room, error: loadError, isLoading, refetch, fulfilledTimeStamp } = useRoomQuery({ code, screen }, { pollingInterval: 2000, refetchOnMountOrArgChange: true, refetchOnFocus: true });
  const [send, { isLoading: busy }] = useRoomCommandMutation();
  const [error, setError] = useState('');
  const [selection, setSelection] = useState({ countryId: '', role: 'president' });
  const [seconds, setSeconds] = useState(720);
  const [now, setNow] = useState(Date.now);
  const [copied, setCopied] = useState(false);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 500); return () => clearInterval(timer); }, []);
  const command = async (kind: string, payload: unknown) => {
    setError('');
    try { await send({ code, kind, payload, requestId: crypto.randomUUID() }).unwrap(); return true; }
    catch (e) { setError(errorMessage(e)); return false; }
  };
  const me = room?.participants.find(p => p.id === room.me);
  const match = isWorldMatch(room?.match) ? room.match : null;
  const own = match?.countries.find(c => c.id === me?.countryId);
  const remaining = match ? Math.max(0, Math.ceil((match.paused ? match.remaining : match.deadline - (match.serverTime + Math.max(0, now - (fulfilledTimeStamp ?? now)))) / 1000)) : 0;
  const expectedPhase = match ? `${match.round}:${match.phase}` : '';
  const authRequired = typeof loadError === 'object' && loadError !== null && 'status' in loadError && loadError.status === 401;
  return <div className="game-shell"><header className="game-header"><Link to="/" className="game-brand"><ArrowLeft size={18} /><b>funtime<span> ✳</span></b></Link><span className="game-header-title">Мировое господство</span><SwitchTheme /></header>
    <main className="game-main" id="main">
      {isLoading && <p role="status">Подключаемся к комнате…</p>}
      {!room && !isLoading && (authRequired ? <section className="game-panel game-enter"><span className="game-kicker">ВАС ЖДУТ ЗА СТОЛОМ</span><h1>Комната {code}</h1><EnterRoom initialCode={code} /></section> : <section className="game-panel"><h1>Не удалось открыть комнату</h1><p role="alert">{errorMessage(loadError)}</p><Button onClick={() => void refetch()}>Повторить</Button></section>)}
      {room && <>
        <div className="game-room-heading"><div><span className="game-kicker">{screen ? 'ОБЩИЙ ЭКРАН' : me?.host ? 'ПУЛЬТ ВЕДУЩЕГО' : me ? `${me.name} · ${roles[me.role] ?? 'Выберите роль'}` : 'КОМНАТА'}</span><h1>{match ? match.phase === 'finished' ? 'Новый мировой порядок' : match.phase === 'council' ? 'Заседание ООН' : 'Работа в штабе' : 'Мир ждёт делегатов'}</h1></div><div className="game-room-code"><small>КОД КОМНАТЫ</small><strong>{code}</strong><button aria-label="Скопировать ссылку приглашения" onClick={async () => { try { await navigator.clipboard.writeText(`${location.origin}/rooms/${code}`); setCopied(true); } catch { setError(`Код для приглашения: ${code}`); } }}><Copy size={16} />{copied ? 'Скопировано' : 'Пригласить'}</button></div></div>
        {loadError && <p className="game-notice" role="status">Связь прервалась. Показаны последние данные; повторяем подключение…</p>}
        {error && <p className="game-notice game-error" role="alert">{error}</p>}
        {!match ? <>
          <div className="game-status-strip"><span><Users size={19} /> {room.participants.length} участников</span><span><Globe2 size={19} /> {new Set(room.participants.map(p => p.countryId).filter(Boolean)).size} стран</span><span><Clock3 size={19} /> 6 раундов · 2 фазы</span></div>
          {!screen && <section className="game-panel"><h2>Ваша страна, ваша роль</h2><p className="game-muted">В каждой команде от 1 до 5 игроков. Роли помогают распределить обязанности; каждый участник может редактировать общий план страны.</p><form className="game-actions" onSubmit={e => { e.preventDefault(); void command('select', selection); }}><label className="game-label">Страна<select required value={selection.countryId} onChange={e => setSelection(v => ({ ...v, countryId: e.target.value }))}><option value="">Выберите страну</option>{room.definition.countries.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="game-label">Роль<select value={selection.role} onChange={e => setSelection(v => ({ ...v, role: e.target.value }))}>{room.definition.roles.map(role => <option key={role} value={role} disabled={room.participants.some(p => p.id !== me?.id && p.countryId === selection.countryId && p.role === role)}>{roles[role]}</option>)}</select></label><Button type="submit" disabled={busy || !selection.countryId || room.status !== 'lobby'}>Занять место</Button></form>{me?.countryId && <p className="game-muted">Вы в команде «{room.definition.countries.find(c => c.id === me.countryId)?.name}», {roles[me.role]}.</p>}</section>}
          <section className="game-panel"><div className="game-section-heading"><h2>Делегации</h2><span className="game-badge">Минимум 2 страны</span></div><div className="game-world-grid">{room.definition.countries.map(c => { const members = room.participants.filter(p => p.countryId === c.id); return <article key={c.id} className={`game-country-card ${me?.countryId === c.id ? 'game-country-own' : ''}`}><div className="game-section-heading"><h3>{c.name}</h3><span className="game-badge">{members.length}/5</span></div><p className="game-muted">{c.cities.join(' · ')}</p>{members.length ? <ul className="game-members">{members.map(p => <li key={p.id}><b>{p.name}{p.id === me?.id ? ' · вы' : ''}</b><span>{roles[p.role]}</span></li>)}</ul> : <p className="game-muted">Места свободны</p>}</article>; })}</div><p className="game-muted">Без команды: {room.participants.filter(p => !p.countryId).map(p => `${p.name}${p.host ? ' (ведущий)' : ''}`).join(', ') || 'все заняли места'}.</p></section>
          {me?.host && !screen && <section className="game-panel"><h2>Начать конгресс</h2><p className="game-muted">В игру войдут страны с участниками. Ведущий может остаться вне команд. Стандартная фаза длится 12 минут; таймер можно приостановить или переключить вручную.</p><div className="game-actions"><label className="game-label">Длительность одной фазы, секунд<input type="number" min={10} max={3600} value={seconds} onChange={e => setSeconds(Number(e.target.value))} /></label><Button disabled={busy || !Number.isInteger(seconds) || seconds < 10 || seconds > 3600} onClick={() => void command('start', { phaseSeconds: seconds })}><Play size={17} />{room.status === 'starting' ? 'Продолжить запуск' : 'Начать игру'}</Button><Link className="game-link" to={`/rooms/${code}/screen`} target="_blank" rel="noreferrer"><Monitor size={18} /> Открыть общий экран</Link></div></section>}
        </> : <>
          <div className="game-status-strip"><span>Раунд <b>{match.round} / 6</b></span><span><Globe2 size={20} /> Экология <b>{match.ecology}%</b></span>{match.phase !== 'finished' && <span className="game-timer"><Clock3 size={20} />{match.paused ? 'Пауза · ' : ''}{Math.floor(remaining / 60).toString().padStart(2, '0')}:{(remaining % 60).toString().padStart(2, '0')}</span>}</div>
          {me?.host && !screen && <section className="game-panel game-host"><div className="game-section-heading"><h2>Управление ведущего</h2><Link className="game-link" to={`/rooms/${code}/screen`} target="_blank" rel="noreferrer"><Monitor size={18} /> Общий экран</Link></div>{match.phase !== 'finished' && <div className="game-actions"><Button variant="secondary" disabled={busy} onClick={() => void command(match.paused ? 'resume' : 'pause', { expectedPhase })}>{match.paused ? <Play size={16} /> : <Pause size={16} />}{match.paused ? 'Продолжить' : 'Пауза'}</Button><Button disabled={busy} onClick={() => void command('advance', { expectedPhase })}><SkipForward size={17} />{match.phase === 'council' ? 'Открыть штабы' : match.round === 6 ? 'Рассчитать и завершить игру' : 'Рассчитать раунд'}</Button></div>}<details><summary>Закрытая сводка ведущего</summary><p className="game-muted">Экология: +{match.formulas?.ecologyImprovement} п.п. за улучшение, −{match.formulas?.bombProductionEcology} п.п. за созданную бомбу. Каждый запуск: −{match.formulas?.launchGlobalDamage} п.п. развития всем городам. Для проектора используйте отдельный общий экран.</p><div className="game-table-wrap"><table><thead><tr><th>Страна</th><th>Бюджет</th><th>План</th><th>Бомбы</th><th>Запуски</th></tr></thead><tbody>{match.countries.map(c => <tr key={c.id}><th>{c.name}</th><td>{coins(c.balanceCents ?? 0)}</td><td>{coins(c.planCostCents ?? 0)}</td><td>{c.bombs} (+{c.plan?.bombs})</td><td>{c.plan?.launches.map(id => match.countries.flatMap(v => v.cities).find(city => city.id === id)?.name).join(', ') || '—'}</td></tr>)}</tbody></table></div><div className="game-two-col">{match.countries.map(c => <details key={c.id}><summary>{c.name} · решения команды</summary><p>Улучшения: {c.plan?.upgrades.map(id => c.cities.find(ct => ct.id === id)?.name).join(', ') || '—'}</p><p>Щиты: {c.plan?.shields.map(id => c.cities.find(ct => ct.id === id)?.name).join(', ') || '—'}</p><p>Программа: {c.plan?.nuclear ? 'создать' : c.nuclearRound ? `готова с раунда ${c.nuclearRound}` : 'нет'} · Экология: {c.plan?.ecology ? 'улучшить' : '—'}</p><p>Санкции: {c.plan?.sanctions.map(id => match.countries.find(v => v.id === id)?.name).join(', ') || '—'}</p><p>Переводы: {c.plan?.donations.map(d => `${match.countries.find(v => v.id === d.countryId)?.name}: ${coins(d.amountCents)}`).join(', ') || '—'}</p></details>)}</div></details></section>}
          {match.phase === 'council' && <section className="game-council"><span className="game-kicker">ЭКСТРЕННЫЙ КОНГРЕСС ООН · 2026</span><h2>{match.round === 1 ? 'Какое будущее обещает ваша страна?' : 'Мир изменился. Что вы скажете делегатам?'}</h2><p>{match.round === 1 ? 'Президент каждой страны представляет свою политику. Стартовый капитал — 1000 монет. Начните с заявления, которое запомнят.' : 'Обсудите обстановку, предложите союз, обвините соперника или призовите к миру. Голосований нет — только слова, пропаганда и психология.'}</p></section>}
          {own?.plan && !screen && match.phase !== 'finished' && <><WorldOrders key={`${own.id}:${match.round}:${match.phase}`} country={own} match={match} command={command} busy={busy} /><WorldDiplomacy country={own} match={match} command={command} busy={busy} /></>}
          <WorldSummary match={match} />
        </>}
        <section className="game-panel"><details><summary>Краткие правила конгресса</summary><div className="game-rules"><p>Побеждает страна с наибольшим средним развитием четырёх городов после шестого раунда. Уничтоженные города считаются за 0%.</p><p>Улучшение города стоит 150: ниже 100% — +20 п.п., от 100% — +25 п.п., от 200% — +100 п.п. Щит за 300 поглощает один удар. Следующий удар уничтожает город навсегда.</p><p>Первый бюджет — 1000. Начиная со второго раунда доход = сумма развития городов × 3 × экология / 100 × (1 − 0,15 × число санкций), минимум 0. Неизрасходованный бюджет сохраняется.</p><p>Ядерная программа — 500. Бомбы по 300 доступны со следующего раунда. Экология — 200. Санкции бесплатны, действуют на доход следующего раунда. Пожертвования анонимны.</p><p>Сохраняйте план до конца штаба: покупки, переводы и удары рассчитываются одновременно. При перерасходе случайные платные действия отменяются. Входящий перевод нельзя потратить в том же расчёте.</p><p>После потери всех городов в следующем раунде можно запустить оставшиеся бомбы, затем страна выбывает. Игра всё равно заканчивается после шестого раунда.</p></div></details></section>
      </>}
    </main><footer className="game-footer">FunTime · Дружба остаётся за дверями конгресса.</footer>
  </div>;
}
