import { useState } from 'react';
import { Trophy, Globe2 } from 'lucide-react';
import { coins, CountryFlag, cityRoles, type WorldMatch } from '@/entities/world-domination';

export function WorldSummary({ match }: { match: WorldMatch }) {
  const [round, setRound] = useState('all');
  const [country, setCountry] = useState('all');
  const ranked = [...match.countries].sort((a, b) => b.score - a.score);
  const name = (id?: string) => match.countries.find(c => c.id === id)?.name ?? 'Анонимно';
  const city = (id?: string) => match.countries.flatMap(c => c.cities).find(c => c.id === id)?.name;
  const finished = match.phase === 'finished';
  const events = match.events.filter(e => (round === 'all' || e.round === Number(round)) && (country === 'all' || e.countryId === country || e.targetId === country));
  const palette = ['#9b81e8', '#48ae92', '#ed946e', '#64a6d6', '#d4ab55', '#df81af', '#98a3ed', '#93b76b', '#d88383', '#a4aabd'];
  const maxScore = Math.max(100, ...match.history.flatMap(h => Object.values(h.scores)));
  return <>
    {finished && <section className="game-victory"><Trophy size={40} /><span className="game-kicker">ШЕСТЬ РАУНДОВ. ОДИН НОВЫЙ МИР.</span><h2>{ranked.filter(c => c.score === ranked[0].score).map(c => c.name).join(' и ')}</h2><p>{ranked.filter(c => c.score === ranked[0].score).length > 1 ? 'Разделяют победу' : 'Новое мировое господство'} · {ranked[0].score}% общего развития</p></section>}
    <section className="game-panel"><div className="game-section-heading"><div><span className="game-kicker">ПУБЛИЧНАЯ СВОДКА</span><h2><Globe2 size={24} /> Состояние мира</h2></div><span className="game-badge">{match.rules.version >= 2 ? `Загрязнение ${match.pollution}%` : `Экология ${match.ecology}%`}</span></div><div className="game-world-grid">{ranked.map((c, i) => <article className="game-country-card" key={c.id}><div className="game-section-heading"><h3><small>{String(i + 1).padStart(2, '0')}</small> <CountryFlag country={c.id} /> {c.name}</h3><strong>{c.score}%</strong></div><div className="game-meter"><span style={{ width: `${Math.min(100,c.score/3)}%`, background: palette[match.countries.findIndex(v => v.id === c.id)] }} /></div><p className="game-muted">{c.eliminated ? 'Страна выбыла' : c.retaliationRound ? `Акт возмездия · раунд ${c.retaliationRound}` : `Среднее развитие ${c.cities.length} городов`}</p>{c.cities.map(ct => <div className="game-city-row" key={ct.id}><span>{ct.name}<small className="game-city-role">{cityRoles[ct.role ?? '']?.name}</small>{ct.destroyed ? ' · уничтожен' : ''}</span><b>{ct.development}%</b></div>)}</article>)}</div></section>
    <section className="game-panel"><h2>Развитие по раундам</h2><div className="game-chart" role="img" aria-label="График среднего развития стран от начала игры до текущего раунда"><svg viewBox="0 0 720 240"><text x="8" y="20">{maxScore}%</text><text x="12" y="205">0%</text>{[0, 1, 2, 3, 4, 5, 6].map(n => <g key={n}><line x1={60 + n * 105} y1="25" x2={60 + n * 105} y2="200" stroke="currentColor" opacity=".1" /><text x={56 + n * 105} y="227">{n}</text></g>)}{match.countries.map((c, i) => <polyline key={c.id} fill="none" stroke={palette[i]} strokeWidth="3" points={match.history.map(h => `${60 + h.round * 105},${200 - (h.scores[c.id] ?? 0) / maxScore * 175}`).join(' ')} />)}{match.countries.flatMap((c,i) => match.history.map(h => <circle key={`${c.id}:${h.round}`} cx={60+h.round*105} cy={200-(h.scores[c.id]??0)/maxScore*175} r="3.5" fill={palette[i]} />))}</svg></div><div className="game-legend">{match.countries.map((c, i) => <span key={c.id}><i style={{ background: palette[i] }} />{c.name}</span>)}</div><details><summary>Показать значения таблицей</summary><div className="game-table-wrap"><table><thead><tr><th>Страна</th>{match.history.map(h => <th key={h.round}>{h.round === 0 ? 'Старт' : `Раунд ${h.round}`}</th>)}</tr></thead><tbody>{match.countries.map(c => <tr key={c.id}><th>{c.name}</th>{match.history.map(h => <td key={h.round}>{h.scores[c.id]}%</td>)}</tr>)}</tbody></table></div></details></section>
    <section className="game-panel"><div className="game-section-heading"><div><span className="game-kicker">{finished ? 'АРХИВ РАССЕКРЕЧЕН' : 'ДОСТУПНАЯ ВАМ ИСТОРИЯ'}</span><h2>{finished ? 'Кто изменил мир' : 'Хроника игры'}</h2></div><div className="game-actions"><select aria-label="Раунд истории" value={round} onChange={e => setRound(e.target.value)}><option value="all">Все раунды</option>{[1, 2, 3, 4, 5, 6].map(n => <option key={n} value={n}>Раунд {n}</option>)}</select><select aria-label="Страна истории" value={country} onChange={e => setCountry(e.target.value)}><option value="all">Все страны</option>{match.countries.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div></div>
      {finished && <div className="game-stats">{match.countries.map(c => <div key={c.id}><strong>{c.name}</strong><span>Запусков: {match.events.filter(e => e.kind === 'attack' && e.countryId === c.id).length}</span><span>Создано бомб: {match.events.filter(e => e.kind === 'production' && e.countryId === c.id).reduce((n,e) => n+(e.amount ?? 0),0)}</span><span>Улучшений экологии: {match.events.filter(e => e.kind === 'ecology' && e.countryId === c.id).length}</span><span>Входящих ударов: {match.events.filter(e => e.kind === 'attack' && e.targetId === c.id).length}</span></div>)}</div>}
      {events.length === 0 ? <p className="game-muted">Пока нет событий по выбранным условиям.</p> : <ol className="game-timeline">{events.slice().reverse().map((e, i) => <li key={i}><span className="game-badge">{e.round}</span><div><b>{name(e.countryId)}{e.targetId ? ` → ${name(e.targetId)}` : ''}{e.cityId ? ` · ${city(e.cityId)}` : ''}</b><p>{e.text}{e.amount ? ` · ${e.kind === 'donation' ? `${coins(e.amount)} монет` : e.amount}` : ''}</p></div></li>)}</ol>}
    </section>
  </>;
}
